# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rechnung-webapp

on:
  push:
    branches:
      - erstattung-master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mmgraz.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_16d87886213a4bd8aaaaf775298f78b2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_72b35375195443fcb49aab01b55b661f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mmgraz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_16d87886213a4bd8aaaaf775298f78b2 }}/rechnung:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rechnung-webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1f7cf74c494243c685f9319a96859e2a }}
        images: 'mmgraz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_16d87886213a4bd8aaaaf775298f78b2 }}/rechnung:${{ github.sha }}'